# Segunda sesion

# 9 agosto

In [3]:
alumno1 = ['Juan', 'Perez', 23]

In [ ]:
alumno1

In [4]:
['Juan', 'Perez', 23]

['Juan', 'Perez', 23]

In [5]:
estadistica_g4 = ['Juan', 'Perez', 'Jimena', 'Alejandra']

In [6]:
type(estadistica_g4)

list

In [7]:
estadistica_g4[0]

'Juan'

In [8]:
estadistica_g4[0],estadistica_g4[2]

('Juan', 'Jimena')

In [9]:
estadistica_g4[0:3]

['Juan', 'Perez', 'Jimena']

In [10]:
estadistica_g4[-1]

'Alejandra'

In [15]:
estadistica_g4.append('Elias')

In [16]:
estadistica_g4

['Juan',
 'Perez',
 'Jimena',
 'Alejandra',
 'Elias',
 'Elias',
 'Elias',
 'Elias',
 'Elias']

In [18]:
estadistica_g4.remove('Elias')

In [19]:
estadistica_g4

['Juan', 'Perez', 'Jimena', 'Alejandra', 'Elias', 'Elias', 'Elias']

In [21]:
estadistica_g4.remove('Elias')

In [24]:
estadistica_g4

['Juan', 'Perez', 'Jimena', 'Alejandra', 'Elias']

## Librerias

In [28]:
pip install yfinance

Note: you may need to restart the kernel to use updated packages.


In [30]:
import yfinance

# Numpy

In [31]:
import numpy as np

In [32]:
edades = [12, 23 ,34, 45 ,56]

In [33]:
type(edades)

list

In [34]:
edades = np.array(edades)

In [35]:
type(edades)

numpy.ndarray

In [37]:
np.sum(edades)

170

In [38]:
np.mean(edades)

34.0

In [40]:
np.prod(edades)

23647680

In [42]:
np.var(edades)

242.0

In [44]:
np.var(edades,ddof=1)

302.5

In [46]:
np.std(edades)

15.556349186104045

In [48]:
np.std(edades,ddof=1)

17.392527130926087

In [51]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [53]:
np.arange(0,101,15)

array([ 0, 15, 30, 45, 60, 75, 90])

In [55]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [57]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [59]:
np.full(6,8)

array([8, 8, 8, 8, 8, 8])

In [80]:
np.random.seed(5)
aleatorios = np.random.randint(0,25,10)

In [81]:
aleatorios

array([ 3, 14, 15,  6, 22, 16,  9,  8,  4,  7])

In [85]:
aleatorios = np.sort(aleatorios)

In [87]:
aleatorios

array([ 3,  4,  6,  7,  8,  9, 14, 15, 16, 22])

In [89]:
aleatorios[2]

6

In [92]:
aleatorios[[2,4]]

array([6, 8])

In [94]:
aleatorios > 10

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [98]:
aleatorios[aleatorios > 10]

array([14, 15, 16, 22])

# Funcion vs Metodo

In [101]:
numeros = [3, 4, 5]

In [111]:
numeros = np.array(numeros)

In [116]:
# funcion

In [112]:
np.mean(numeros)

4.0

In [ ]:
# Metodo

In [113]:
numeros.mean()

4.0

In [ ]:
# Funcion

In [114]:
round(np.mean(np.array(numeros)),2)

4.0

In [ ]:
# Metodo

In [115]:
np.array(numeros).mean().round(2)

4.0